run:
  timeout: 5m
  tests: true
  skip-files:
    - websocket_test.go
linters-settings:
  goimports:
    local-prefixes: goftx,github
linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - depguard
    - goimports
  enable-all: false
  disable-all: true
